### ISSUE TITLE
Failed icons placement on windows.

### ISSUE THREAD

**Issue by havenchyk** [roman01la/anybar-webpack#1]
Following  https://github.com/roman01la/most-react/issues/1.

I've got this error on windows 7. Any workaround for windows users are welcomed :smile:

```
npm ERR! node v0.12.0
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! anybar-webpack@1.0.4 place-icons: `mkdir -p ~/.AnyBar && cp ./lib/icons/webpack-* ~/.AnyBar/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the anybar-webpack@1.0.4 place-icons script 'mkdir -p ~/.AnyBar && cp ./lib/icons/webpack-* ~/.AnyBar/'.
npm ERR! This is most likely a problem with the anybar-webpack package,
npm ERR! not with npm itself.
```

**Comment by roman01la** [comment]
I've published temporary version. Try to run `npm i anybar-webpack@1.0.4-non-macos`, this will install plugin, but on Windows you should get the following message `anybar-webpack plugin is for Mac OS only app AnyBar.` with no installation error. I've tested this one, so let me know if it works for you. I'll merge it into master and update all projects which are depends on this plugin.

**Comment by havenchyk** [comment]
It works for me, there is no any error. Thanks!
