### ISSUE TITLE
`Question`: Remove unnecessary files from npm snapshot

### ISSUE THREAD

**Issue by havenchyk** [roman01la/anybar-webpack#4]
Hi Roman,

After installing package to my project I see _maybe_ unnecessary file in the `node_modules`.

Here is structure I see:

```
CHANGELOG.md
LICENSE
README.md
app.js
app.min.js
app.min.js.map
bin
icons.svg
lib
package.json
test
webpack.config.js
```

What do you think about excluding some fiiles from npm? I guess that files like webpack.config or changelog.md shouldn't be in the npm and I'm interesting in your opinion here.

**Comment by havenchyk** [comment]
@roman01la what do you think?

**Comment by roman01la** [comment]
Oh snap! You are right, I've put some unnecessary files 😅

**Comment by roman01la** [comment]
Done!

**Comment by havenchyk** [comment]
@roman01la thanks! It's a magic for me, how you've excluded files without changing of `.npmignore`. Could you share your recipes? :)

**Comment by roman01la** [comment]
I had uncommitted files, so they got into NPM package, but not into the repo.
